# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  push:
    branches:
      - main
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "22 22 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: iomz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Zurich
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: c, html, java, matlab, css, tex, less, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 400
          plugin_languages_sections: recently-used
          plugin_languages_threshold: 10%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          #plugin_notable: yes
          #plugin_repositories: yes
          #plugin_repositories_featured: bibfuse, radicron, dl-myo
          #plugin_repositories_order: featured, pinned, starred
          #plugin_repositories_pinned: 4
          #plugin_repositories_starred: 4
          #plugin_stars: yes
          #plugin_stars_limit: 4
